### ISSUE TITLE
Include check parameters when generating linter.toml file

### ISSUE THREAD

**Issue by tjwaterman99** [checkers-dev/checkers#8]
This should make it easier for users to tweak their configuration.

**Comment by tjwaterman99** [comment]
Currently generates a toml file like the following:

```toml
dbt_project_dir = "/workspaces/checkers/tests/mock"
api_host = "http://127.0.0.1:3000/api"

[checks.check_model_has_description]
enabled = true
minimum_description_length = 10
minimum_description_words = 4

[checks.check_custom_check]
enabled = true
```
